### ISSUE TITLE
Admin Login?

### ISSUE THREAD

**Issue by samatzhusup** [Prince-Shivaram/BookStore-App#1]
hello! how can i get to the admin panel?

**Comment by Prince-Shivaram** [comment]
Hi @samatzhusup 
**Follow these steps:**
- You can fork the project & clone that repo into your local machine
- Then set up the project in your local machine through the instructions in the readme file
- Don't forget to add .env file, you can use the same file structure mentioned in the readme file
- add your mongo_URI, JWT_secret & PayPal client ID
- Then, do 'npm install' in the project folder and in the frontend folder
- Finally, run the command 'npm run dev' to start the project
